spring:
  datasource:
    url: jdbc:postgresql://dpg-cr2bgurv2p9s738ddn30-a.singapore-postgres.render.com/hangulsarang?sslmode=require # PostgreSQL 연결 URL
    username: hjkeem
    password: ndu3CV8NALUCTx1Yy59FCMGsrWHC29jJ
    driver-class-name: org.postgresql.Driver  # PostgreSQL 드라이버 클래스
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQL에 맞는 Hibernate Dialect
    hibernate:
      ddl-auto: create
  web:
    resources:
      add-mapping: true
      static-locations: classpath:/static/
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
  servlet:
    session:
      timeout: 30m #30분으로 설정
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 3ba205a8f7ed3ada9771391acb9dddf6 # 카카오 개발자 콘솔에서 발급받은 REST API 키
            scope: profile_nickname, profile_image
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
